export enum SocialPlatform {
  FACEBOOK = "FACEBOOK",
  INSTAGRAM = "INSTAGRAM",
  MESSENGER = "MESSENGER",
  WHATSAPP = "WHATSAPP",
  TIKTOK = "TIKTOK",
  YOUTUBE = "YOUTUBE",
  LINKEDIN = "LINKEDIN",
  X = "X",
  PINTEREST = "PINTEREST",
  THREADS = "THREADS",
}

export enum FunnelStage {
  NEW_LEAD = "NEW_LEAD",
  CONTACTED = "CONTACTED",
  INTERESTED = "INTERESTED",
  QUALIFIED = "QUALIFIED",
  APPOINTMENT = "APPOINTMENT",
  PROPOSAL_SENT = "PROPOSAL_SENT",
  NEGOTIATION = "NEGOTIATION",
  WON = "WON",
  LOST = "LOST",
}

export enum OrgRole {
  OWNER = "OWNER",
  MANAGER = "MANAGER",
  MARKETING = "MARKETING",
  SALES = "SALES",
  SUPPORT = "SUPPORT",
}

export enum ContentType {
  POST = "POST",
  CAROUSEL = "CAROUSEL",
  POSTER = "POSTER",
  PRODUCT_PHOTO = "PRODUCT_PHOTO",
  GRAPHIC = "GRAPHIC",
  VIDEO = "VIDEO",
  REEL = "REEL",
  SHORT = "SHORT",
  TIKTOK_VIDEO = "TIKTOK_VIDEO",
  BLOG_ARTICLE = "BLOG_ARTICLE",
  LANDING_PAGE = "LANDING_PAGE",
  EMAIL_CAMPAIGN = "EMAIL_CAMPAIGN",
  SMS_CAMPAIGN = "SMS_CAMPAIGN",
  WHATSAPP_CAMPAIGN = "WHATSAPP_CAMPAIGN",
}

export enum AgentKind {
  DOMO = "DOMO",
  CONTENT_CREATOR = "CONTENT_CREATOR",
  SOCIAL_MEDIA_MANAGER = "SOCIAL_MEDIA_MANAGER",
  COPYWRITER = "COPYWRITER",
  VIDEO_CREATOR = "VIDEO_CREATOR",
  IMAGE_CREATOR = "IMAGE_CREATOR",
  LEAD_QUALIFIER = "LEAD_QUALIFIER",
  CRM_MANAGER = "CRM_MANAGER",
  CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT",
  ANALYTICS = "ANALYTICS",
  CAMPAIGN_OPTIMIZER = "CAMPAIGN_OPTIMIZER",
  TREND_RESEARCH = "TREND_RESEARCH",
  SEO = "SEO",
}

export enum PlanTier {
  STARTER = "STARTER",
  PROFESSIONAL = "PROFESSIONAL",
  BUSINESS = "BUSINESS",
  ENTERPRISE = "ENTERPRISE",
}
